// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import ClipboardController from "./clipboard_controller"
import RemovalsController from "./removals_controller"
import SearchController from "./search_controller"



application.register("clipboard", ClipboardController)
application.register("removals", RemovalsController)
application.register("search", SearchController)
