// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import FormvalidatorController from "./formvalidator_controller"
application.register("formvalidator", FormvalidatorController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import SearchController from "./search_controller"
application.register("search", SearchController)
